name: Changelog

on:
  push:
    tags:
      - '**'

jobs:
  editing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          npm install
      - name: Changelog editing
        run: |
          npm run version